config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'


  namespace :admin do
    resources :customers
  end


  namespace :public do

    resources :voice_posts do
      resource :favorites
      resources :comment_posts
    end

    resources :customers do
      resource :relationships
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      collection do
        get 'search'
      end
    end

    get 'homes/top/sort/new', to: 'homes#top', as: 'sort_new'
    get 'homes/top/sort/favorites', to: 'homes#top', as: 'sort_favorites'
    get 'voice_posts/index/sort/new', to: 'voice_posts#index'
    get 'voice_posts/index/sort/favorites', to: 'voice_posts#index'



    get '/voice_posts/hashtag/:name' => "voice_posts#hashtag", as: "hashtag"

  end


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image

  has_many :voice_posts, dependent: :destroy
  has_many :comment_posts, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, presence: true
  validates :email, presence: true


  def get_image
    if image.attached?
      image
    else
      'no_image.png'
    end
  end

  def follow(customer_id)
    relationships.create(followed_id: customer_id)
  end

  def unfollow(customer_id)
    relationships.find_by(followed_id: customer_id).destroy
  end

  def following?(customer)
    followings.include?(customer)
  end

   def self.guest
    find_or_create_by!(name: 'guestcustomer' ,email: 'guestcustomer@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "guestcustomer"
    end
   end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def destroy
    @customers = Customer.find(params[:id])
    @customers.destroy
    redirect_to admin_customers_path
  end

  def show
    #error後の更新時indexに移ってしまうため
    if params[:id]
      redirect_to edit_admin_customer_path
      return
    end
  end

  def edit
    @customers = Customer.find(params[:id])
  end

  def update
    @customers = Customer.find(params[:id])
    if @customers.update(customer_params)
      redirect_to admin_customers_path
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :image, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <% if @customers.errors.any? %>
        <div class = "col-4">
          <%= @customers.errors.count %>件のエラーが発生しました
          <ul>
            <% @customers.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <table class = "newtable" width = "100%">
      <thead>
        <tr align="center">
          <td colspan="2"><font size=6px>会員情報編集</td>
        </tr>
      </thead>
       <tbody>
          <%= form_with model: @customers, url: admin_customer_path, metdod: :patch do |f| %>
            <tr><td class = "text-right", width = "50%">name</td><td class = "text-left"><%= f.text_field :name %></td></tr>
            <tr><td class = "text-right">email</td><td class = "text-left"><%= f.text_area :email %></td></tr>
            <tr><td class = "text-right"><%= f.label :is_deleted, "有効" %></td><td class = "text-left"><%= f.radio_button :is_deleted, false %></td></tr>
            <tr><td class = "text-right"><%= f.label :is_deleted, "退会" %></td><td class = "text-left"><%= f.radio_button :is_deleted, true %></td></tr>
            <tr><td class = "text-center",  colspan="2"><%= f.submit 'update' %></td></tr>
           <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class = "col">
      <table width = "100%">
        <thead>
          <tr align="center">
            <th colspan="5"><font size=6px></i>会員一覧</th>
          </tr>
        </thead>
         <tbody>
            <tr class = "text-center">
              <td>name</td>
              <td>image</td>
              <td>email</td>
              <td>status</td>
             </tr>
            <% @customers.each do |customers| %>
            <tr class = "text-center">
              <td><%= link_to customers.name, edit_admin_customer_path(customers), class:"hoge", data: {"turbolinks"=>false} %></td>
              <td><%= image_tag customers.get_image, size: '100x100' %></td>
              <td><%= customers.email %></td>
              <td><% if customers.is_deleted == false %>
                    会員
                  <% else %>
                    退会
                  <% end %>
              </td>
              <td><%= link_to "削除", admin_customer_path(customers), method: :delete %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>