config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'


  namespace :admin do
    resources :customers
  end


  namespace :public do

    resources :voice_posts do
      resource :favorites
      resources :comment_posts
    end

    resources :customers do
      resource :relationships
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      collection do
        get 'search'
      end
    end

    get 'homes/top/sort/new', to: 'homes#top', as: 'sort_new'
    get 'homes/top/sort/favorites', to: 'homes#top', as: 'sort_favorites'
    get 'voice_posts/index/sort/new', to: 'voice_posts#index'
    get 'voice_posts/index/sort/favorites', to: 'voice_posts#index'



    get '/voice_posts/hashtag/:name' => "voice_posts#hashtag", as: "hashtag"

  end


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YomiKikase</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar justify-content-center bg-transparent">
      <div class="container-fluid justify-content-center">
         <%= link_to root_path  do %>
          <%= image_tag 'Logo.png', size: '150x120' %>
         <% end %>
      </div>
      <div class="container-fluid justify-content-center">
        <!--管理側と顧客側でヘッダーのリンクを分岐-->
        <% if request.path&.include?('/admin/') %>
          <% if admin_signed_in? %>
            <div class="col texit-white">
              <%= link_to "sign out", destroy_admin_session_path, method: :delete, class:"Editlink" %>
            </div>
            <div class="col texit-white">
              <%= link_to "customer index", admin_customers_path, class:"Editlink" %>
            </div>
          <% else %>
            <div class="col texit-white">
              <%= link_to "log in", new_admin_session_path, class:"Editlink" , data: {"turbolinks"=>false} %>
            </div>
          <% end %>
        <% else %>
          <% if customer_signed_in? %>
            <div class="col texit-white">
              <%= link_to "my page", {controller: 'voice_posts', action: 'index', id: current_customer.id}, class:"Editlink" %>
            </div>
            <div class="col">
              <%= link_to "new", new_public_voice_post_path, class:"Editlink", data: {"turbolinks"=>false} %>
            </div>
            <div class="col">
              <%= link_to "search", search_public_customers_path, class:"Editlink" %>
            </div>
             <div class="col text-center">
              <%= link_to "log out", destroy_customer_session_path, method: :delete, class:"Editlink" %>
            </div>
          <% else %>
            <div class="col texit-white">
              <%= link_to "sign up", new_customer_registration_path, class:"Editlink", data: {"turbolinks"=>false}  %>
            </div>
            <div class="col">
              <%= link_to "log in", new_customer_session_path, class:"Editlink", data: {"turbolinks"=>false}  %>
            </div>
            <div class="col">
              <%= link_to 'guest log in', public_guest_sign_in_path, method: :post, class:"Editlink" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </nav>
    <div class = "partbody">
      <%= yield %>
    </div>
  </body>
</html>